site_name: My Second Brain
site_url: https://hellojowet.github.io/second_brain
theme:
  name: material
  features:
    # code copy button
    - content.code.copy
  palette: 
    - scheme: slate
markdown_extensions:
  # code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # permalinks
  - toc:
      permalink: true
  # call outs
  - admonition
plugins:
  # simplification of page configuration
  - search
  - awesome-pages